import type { Metadata } from "next";

import "../styles/normalize.css"
import "../styles/skeleton.css"
import "../styles/globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
            <div className="container">
                {children}
            </div>
        </body>
        </html>
    );
}
